"""added unique constraint to fruit name

Revision ID: 470d57c10c76
Revises: 6511990fad4b
Create Date: 2026-08-05 13:22:48.610674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470d57c10c76'
down_revision: Union[str, Sequence[str], None] = '6511990fad4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fruits_name'), 'fruits', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fruits_name'), table_name='fruits')
    # ### end Alembic commands ###
